### ISSUE TITLE
Document Error (too old).

### ISSUE THREAD

**Issue by AndroidLinux** [dotnet/dotnet-api-docs.zh-tw#6]
Describe of  argument millisecondsTimeout

If the value of the millisecondsTimeout argument is Zero, the thread relinquishes the remainder of its time slice to any thread of equal priority that is ready to run. 

Should be (References from SleepEx Function)

A value of zero causes the thread to relinquish the remainder of its time slice to any other thread that is ready to run.  If there are no other threads ready to run, the function returns immediately, and the thread continues execution.Windows XP:  A value of zero causes the thread to relinquish the remainder of its time slice to any other thread of equal priority that is ready to run.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 64356b6a-37b6-40f5-60c2-e19c2e7baecb
* Version Independent ID: 124b7ab8-bc94-dd09-0c2a-2289fdf6e1a1
* Content: [Thread.Sleep Method (System.Threading)](https://docs.microsoft.com/zh-tw/dotnet/api/system.threading.thread.sleep?view=netframework-4.8#feedback)
* Content Source: [xml/System.Threading/Thread.xml](https://github.com/dotnet/dotnet-api-docs.zh-tw/blob/live/xml/System.Threading/Thread.xml)
* Product: **dotnet-api**
* Technology: **system.threading**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @AndroidLinux
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @JasonCard 
The contributor comments refer to the original documentation but I can't move the issue to the en-us repo because it's not available. 
Can you please check this? thanks in advance

**Comment by JasonCard** [comment]
@mairaw We want to move this issue to en-us repo (dotnet-api-docs) and usually use ZenHub, but it appears that dotnet-api-docs repo is not available in ZenHub for some reason. Do you have any idea of recent change that maybe causing this? cc @CeciAc

**Comment by CeciAc** [comment]
Hello, @AndroidLinux 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/dotnet-api-docs/issues/2699

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
