### ISSUE TITLE
Expression<TDelegate> 解釋

### ISSUE THREAD

**Issue by MickeyShiue** [dotnet/dotnet-api-docs.zh-tw#7]
可否將=&gt; 將強類型 Lambda 運算式表示為運算式樹狀架構形式的資料結構。 這個類別無法被繼承。
改為=&gt; 將 Lambda 用樹狀架構形式的資料結構來表示

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: c7fdaea5-d11f-bbd9-60b7-074cdb222c47
* Version Independent ID: 9665d6b3-fc16-986a-7361-9283c722d0d7
* Content: [Expression&lt;TDelegate&gt; Class (System.Linq.Expressions)](https://docs.microsoft.com/zh-tw/dotnet/api/system.linq.expressions.expression-1?view=netframework-4.8#feedback)
* Content Source: [xml/System.Linq.Expressions/Expression`1.xml](https://github.com/dotnet/dotnet-api-docs.zh-tw/blob/live/xml/System.Linq.Expressions/Expression`1.xml)
* Product: **dotnet-api**
* Technology: **system.linq**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @MickeyShiue
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
您好，@MickeyShiue，  
謝謝您的寶貴意見。 
我們的編審小組審閱了您提出的語言建議，並接受了這些建議。我們已實作您的意見反應並發佈至 Docs 網站上已更新文章的以下頁面 https://docs.microsoft.com/zh-tw/dotnet/api/system.linq.expressions.expression-1?view=netframework-4.8#feedback
我們由衷感謝您對文章的貢獻，並期望您繼續提供寶貴的意見。 
順頌時祺 
Microsoft DOCS 國際小組
